config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :events do
    collection do
      get 'search'
    end
    resources :registers
  end
  resources :musicians
  root 'welcome#index'

  get '/khmer' => 'welcome#khmer'
  get '/western' => 'welcome#western'
end

app/models/register.rb
class Register < ActiveRecord::Base
  belongs_to :event

  validates :firstname, :lastname, :gender, :address, presence: true
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]
  before_action :set_event
  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = @event.registers.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @event = Event.find(params[:event_id])
    @register = @event.registers.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to @event, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end
    def set_event
      @event = Event.find(params[:event_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:firstname, :lastname, :gender, :address, :email)
    end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<%= form_for([@event, @register]) do |f| %>
<% if @register.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

  <ul>
    <% @register.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :firstname %><br>
  <%= f.text_field :firstname, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :lastname %><br>
  <%= f.text_field :lastname, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :gender %><br>
  <%= f.text_field :gender, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :address %><br>
  <%= f.text_field :address, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :email %><br>
  <%= f.text_field :email, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.submit class:'btn btn-success' %>
</div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registers</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Gender</th>
      <th>Address</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.firstname %></td>
        <td><%= register.lastname %></td>
        <td><%= register.gender %></td>
        <td><%= register.address %></td>
        <td><%= register.email %></td>
        <td><%= link_to 'Show', event_register_path(@event,register) %></td>
        <td><%= link_to 'Edit', edit_event_register_path(@event,register) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Register', new_event_register_path %>

app/views/registers/new.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title" id="myModalLabel">Registration</h2>
    </div>
    <div class="modal-body">
    <legend class="text-center"><%= @event.title %></legend>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
         <%= render 'form' %>
       </div>
     </div>
   </div>
   <div class="modal-footer" style="border: none">
     <%= link_to 'Cancel', event_path(@event), class: "btn btn-default" %>
   </div>
 </div>
</div>
</div>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @register.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @register.lastname %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @register.gender %>
</p>

<p>
  <strong>Address:</strong>
  <%= @register.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @register.email %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>