config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :events do
    collection do
      get 'search'
    end
    resources :registers
  end
  resources :musicians
  root 'welcome#index'

  get '/khmer' => 'welcome#khmer'
  get '/western' => 'welcome#western'
end

app/models/musician.rb
class Musician < ActiveRecord::Base
  belongs_to :origin
  belongs_to :user

  validates :name, :genre, :origin, presence: true
  validates :description, presence: true, length: {minimum: 20}

  if Rails.env.development?
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: 'default.png'
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  else
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: 'default.png',
                      :storage => :dropbox,
                      :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                      :path => ":style/:id_:filename"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  end

  rails_admin do
    navigation_icon 'icon-music'
    label " Band"
    list do
      field :image
      field :name
      field :description
      field :genre
      field :origin
    end

    edit do
      field :name
      field :description
      field :genre
      field :origin
      field :image
    end
  end
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  before_action :set_musician, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /musicians
  # GET /musicians.json
  def index
    if params[:origin_id]
      @musicians = Musician.where(origin_id: params[:origin_id])
    else
      @musicians = Musician.all
    end
  end

  # GET /musicians/1
  # GET /musicians/1.json
  def show
  end

  # GET /musicians/new
  def new
    @musician = Musician.new
  end

  # GET /musicians/1/edit
  def edit
  end

  # POST /musicians
  # POST /musicians.json
  def create
    @musician = Musician.new(musician_params)
    @musician.user_id = current_user.id
    respond_to do |format|
      if @musician.save
        format.html { redirect_to @musician, notice: 'Musician was successfully created.' }
        format.json { render :show, status: :created, location: @musician }
      else
        format.html { render :new }
        format.json { render json: @musician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musicians/1
  # PATCH/PUT /musicians/1.json
  def update
    respond_to do |format|
      if @musician.update(musician_params)
        format.html { redirect_to @musician, notice: 'Musician was successfully updated.' }
        format.json { render :show, status: :ok, location: @musician }
      else
        format.html { render :edit }
        format.json { render json: @musician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musicians/1
  # DELETE /musicians/1.json
  def destroy
    @musician.destroy
    respond_to do |format|
      format.html { redirect_to musicians_url, notice: 'Musician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musician
      @musician = Musician.find(params[:id])
    end

    def check_user
      unless @musician.user == current_user
        redirect_to root_url, alert: "Sorry, this gigs belongs to someone else."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def musician_params
      params.require(:musician).permit(:name, :description, :genre, :origin_id, :image)
    end
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/views/musicians/_form.html.erb
<%= form_for @musician, html: { multipart: true } do |f| %>
<% if @musician.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@musician.errors.count, "error") %> prohibited this musician from being saved:</h2>

  <ul>
    <% @musician.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-group">
  <%= f.label :name %><br>
  <%= f.text_field :name, class:'form-control' %>
</div>
<div class="form-group">
  <%= f.label :description %><br>
  <%= f.text_area :description, class:'form-control' %>
</div>
<div class="form-group">
  <%= f.label :genre %><br>
  <%= f.text_field :genre, class:'form-control', placeholder: 'ex: Rock, Pop, Jazz, Hip-Hop, Rap ...' %>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-md-3">
      <%= f.label :Origin %> <br>
      <%= f.collection_select :origin_id, Origin.all, :id, :name, { prompt: "Choose a Category"}, class:'form-control' %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-md-5">
      <%= f.label :image %><br>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
  </div>
</div>
<div class="form-group">
  <%= f.submit class: 'btn btn-primary' %>
</div>
<% end %>

app/views/musicians/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <h1>Editing Musician</h1>
        <%= render 'form' %>
        <%= link_to 'Show', @musician, class:'btn btn-link' %> |
        <%= link_to 'Cancel', musician_path, class:'btn btn-link' %>
    </div>
  </div>
</div>

app/views/musicians/index.html.erb
<div class="container">
  <div class="row">
  <div class="band-index">
      <h1> Band</h1>
  </div>

    <% @musicians.each do |musician| %>
    <div class="col-md-6">
      <div class="row">
        <% if musician.origin_id == 1 %>
        <div class="col-md-5">
          <%= image_tag musician.image, size: '200x200' %>
        </div>
        <div class="col-md-7">
          <h5>Brand Name: <%= musician.name %></h5>
          <p>Description: <%= musician.description %> </p>
          <p>Genre: <%= musician.genre %></p>
          <p>Origin: <%= musician.origin.name %></p>
          <%= link_to 'Show', musician %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
<!-- Western Band -->

    <% @musicians.each do |musician| %>
    <div class="col-md-6">
      <div class="row">
        <% if musician.origin_id == 2 %>
        <div class="col-md-5">
          <%= image_tag musician.image, size: '200x200' %>
        </div>
        <div class="col-md-7">
          <h5>Brand Name: <%= musician.name %></h5>
          <p>Description: <%= musician.description %> </p>
          <p>Genre: <%= musician.genre %></p>
          <p>Origin: <%= musician.origin.name %></p>
          <%= link_to 'Show', musician %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>

  </div>
  <br>
  <%= link_to "New Band", new_musician_path, class: "btn btn-default" %>
</div>

app/views/musicians/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <h1>New Musician</h1>
      <%= render 'form' %>
      <%= link_to 'Cancel', musicians_path, class:'btn btn-link' %>
    </div>
  </div>
</div>

app/views/musicians/show.html.erb
<div class="container">
  <div class="show-content">
    <div class="musician-banner">
    </div>
    <div class="group-description">
      <div class="row">
        <div class="col-md-5 image-content">
          <%= image_tag @musician.image.url, size: '430x500' %>
        </div>
        <div class="col-md-6 doc-content">
          <% if user_signed_in? %>
          <% if @musician.user == current_user %>
          <%= link_to 'Edit', edit_musician_path(@musician), class: 'btn btn-info' %> |
          <%= link_to 'Delete', musician_path, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
          <% end %>
          <% end %>
          <p>
            <strong>Brand Name:</strong>
            <%= @musician.name %>
          </p>
          <p>
            <strong>Description:</strong>
            <%= @musician.description %>
          </p>
          <p>
            <strong>Genre:</strong>
            <%= @musician.genre %>
          </p>
          <p>
            <strong>Origin:</strong>
            <%= @musician.origin.name %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>