config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :events do
    collection do
      get 'search'
    end
    resources :registers
  end
  resources :musicians
  root 'welcome#index'

  get '/khmer' => 'welcome#khmer'
  get '/western' => 'welcome#western'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :origin
  belongs_to :user
  has_many :registers

  scope :khmer, -> { where(origin_id: 1).order('created_at DESC') }
  scope :western, -> { where(origin_id: 2).order('created_at DESC') }
  scope :current_event, -> { where('start_on BETWEEN ? AND ?', Date.current.beginning_of_day, Date.current.end_of_day).order(created_at: :DESC).limit(9) }
  scope :yesterday_event, -> { where('start_on BETWEEN ? AND ?', Date.yesterday.beginning_of_day, Date.yesterday.end_of_day).order(created_at: :DESC).limit(9) }

  validates :title, :genre, :venue, :location, :origin, presence: true
  validates :description, presence: true, length: {minimum: 50}

  if Rails.env.development?
    has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: 'default.png'
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  else
    has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: 'default.png',
                      :storage => :dropbox,
                      :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                      :path => ":style/:id_:filename"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  end

  include PgSearch
  pg_search_scope :search,
                  against: %i(
                    title
                    location
                    genre
                    venue
                  ),
                  using: {
                    tsearch: {
                      dictionary: 'english',
                      any_word: true,
                      prefix: true
                    }
                  }

  rails_admin do
    navigation_icon 'icon-calendar'
    label " Gigs"
    list do
      field :image
      field :title
      field :description
      field :start_on
      field :genre
      field :venue
      field :location
      field :origin
    end

    edit do
      field :title
      field :description
      field :start_on
      field :genre
      field :venue
      field :location
      field :origin
      field :image
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search,:show]
  before_action :check_user, only: [:edit, :update, :destroy]

  def search
      @events = Event.search(params[:search])
  end

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit

  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    respond_to do |format|
      if @event.save
        EventMailer.create_event_mailer(@event).deliver
        format.html { redirect_to @event, notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def check_user
      unless @event.user == current_user
        redirect_to root_url, alert: "Sorry, this gigs belongs to someone else."
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :venue, :location, :image, :start_on, :genre, :origin_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, :html => { :multipart => true }) do |f| %>
<% if @event.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

  <ul>
    <% @event.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :title %><br>
  <%= f.text_field :title, class:'form-control' %>
</div>
<div class="form-group">
  <%= f.label :description %><br>
  <%= f.text_area :description, class:'form-control' %>
</div>
<div class="form-group">
  <%= f.label :start_on %><br>
  <%= f.date_field :start_on %>

</div>
<div class="form-group">
  <%= f.label :start_on %><br>
  <%= f.time_field :start_on %>
</div>
<div class="form-group">
  <%= f.label :genre %><br>
  <%= f.text_field :genre, class:'form-control', placeholder: 'ex: Rock, Pop, Jazz, Hip-Hop, Rap ...' %>
</div>
<div class="form-group">
  <%= f.label :venue %><br>
  <%= f.text_field :venue, class:'form-control', placeholder:'ex: Devbootstrap Innovation...' %>
</div>
<div class="form-group">
  <%= f.label :location %><br>
  <%= f.text_field :location, class:'form-control', placeholder: 'ex: #296, 271 Yothapol Khemarak Phoumin Blvd, Phnom Penh, Cambodia' %>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-md-3">
      <%= f.label :Origin, class: "control-label" %> <br>
      <%= f.collection_select :origin_id, Origin.all, :id, :name, { prompt: "Choose a Origin"}, class:'form-control' %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="row">
    <div class="col-md-5">
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
  </div>
</div>

<div class="actions">
  <%= f.submit class:'btn btn-primary' %>
</div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <h1>Editing Gigs</h1>
        <%= render 'form' %>
        <%= link_to 'Show', @event, class:'btn btn-link' %> |
        <%= link_to 'Back', events_path, class:'btn btn-link' %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<h1>Listing Gigs</h1>
<%= link_to 'New Event', new_event_path %>
<table class="table table-splite">
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Description</th>
      <th>Start On</th>
      <th>Genre</th>
      <th>Venue</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= image_tag event.image.url, size: '100x100' %></td>
        <td><%= event.title %></td>
        <td><%= truncate(event.description, length: 50) %></td>
        <td><%= event.start_on %></td>
        <td><%= event.genre %></td>
        <td><%= event.venue %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <h1>New Gigs</h1>
          <%= render 'form' %>
          <%= link_to 'Cancel', root_url, class:'btn btn-link' %>
    </div>
  </div>
</div>

app/views/events/search.html.erb
<div class="container-fluid">
  <%= render 'layouts/banner' %>
</div>
<div class="container">
<div class="row">
  <div class="col-md-8 col-md-off-2 search">
  <%= form_tag search_events_path, method: :get do %>
  <div class="col-md-10">
  <%= text_field_tag :search, params[:search], class: 'form-control glyphicon glyphicon-search', placeholder:"Search title, genre, venue, location" %>
  </div>
  <%= submit_tag 'Search', name: nil, class: 'btn btn-danger' %>
  <% end %>
  </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <h1 class="text-center">Listing Gigs</h1>
    <% if @events.count == 0 %>
    <h1 class="text-center">No Result</h1>
    <% else %>
    <% @events.each do |event| %>
    <div class="col-md-4">
      <div class="main-photo">
        <%= link_to (image_tag(event.image, size: '400x200', class:'nametag-photo')), event_path(event) %>
        <div class="group-title">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <p><%= link_to event.start_on.strftime("%Y %m %d %I %M %p"), event_path(event) %></p>
          <p><%= link_to truncate(event.location, length: 50), event_path(event) %></p>
        </div>
      </div>
    </div>
    <% end %>

    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="show-content">
    <div class="chapter-banner">
      <h1><%= @event.title %></h1>
    </div>
    <div class="group-description">
      <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-5 image-content">
        <%= image_tag @event.image.url, size: '430x500', class: 'img-responsive' %>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6 doc-content">
          <% if (user_signed_in?) && (@event.user == current_user) %>
          <%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-info' %> |
          <%= link_to 'Delete', event_path, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
          <% else %>
          <%= link_to 'Join Us', new_event_register_path(@event),:data => {:toggle => "modal"}, :data =>{:target =>"#myModal'"}, class: 'btn btn-success' %>
          <% end %>
          <%= pluralize(@event.registers.size, 'Member') %>

          <h3>Description:</h3>
          <p><%= @event.description %></p>
          <p>
            <strong>Start Date:</strong>
            <%= @event.start_on.strftime("%Y %m %d") %>
          </p>
          <p>
            <strong>Start Time:</strong>
            <%= @event.start_on.strftime(" %I %M %p") %>
          </p>
          <p>
            <strong>Genre:</strong>
            <%= @event.genre %>
          </p>
          <p>
            <strong>Venue:</strong>
            <%= @event.venue %>
          </p>
          <p>
            <strong>Location:</strong>
            <%= @event.location %>
          </p>
          <p>
            <strong>Origin:</strong>
            <% if @event.origin.id == 1 %>
            <%=  @event.origin.name %>
            <% elsif @event.origin.id == 2 %>
            <%=  @event.origin.name %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>