config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :events do
    collection do
      get 'search'
    end
    resources :registers
  end
  resources :musicians
  root 'welcome#index'

  get '/khmer' => 'welcome#khmer'
  get '/western' => 'welcome#western'
end

app/views/layouts/_banner.html.erb
<div class="row banner-img">
    <!-- The carousel -->
    <div id="transition-timer-carousel" class="carousel slide transition-timer-carousel" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#transition-timer-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#transition-timer-carousel" data-slide-to="1"></li>
    <li data-target="#transition-timer-carousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
                <img src="http://img1.meetupstatic.com/img/65793887588307544/explore_page_photos/find-8.jpg" />
            </div>
            <div class="item">
                <img src="http://img1.meetupstatic.com/img/37938458543495657/explore_page_photos/find-11.jpg" />
            </div>
            <div class="item">
                <img src="http://img1.meetupstatic.com/img/650788672797009687495346/explore_page_photos/find-4.jpg" />
            </div>
        </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#transition-timer-carousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#transition-timer-carousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>

        <!-- Timer "progress bar" -->
        <hr class="transition-timer-carousel-progress-bar animate" />
</div>
</div>

app/views/layouts/_footer.html.erb
<hr>
<div class="footer bg-navbar footer-link">
<div style="text-align:center">
  <%= link_to 'About', pages_about_path %>
  <%= link_to 'Contact', pages_contact_path %>
</div>

<p style="text-align:center">    Copyright &copy; 2015.
    <%= link_to ' Devboostrap Gigs Team', root_path %></p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default bg-navbar">
  <div class="container ">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'DB Gigs', root_path, class: "navbar-brand logo_brand btn btn-danger" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav menu-link">
        <% Origin.all.each do |origin| %>
        <% if origin.id == 1 %>
        <li>
          <a href="#">Gigs &#9662;</a>
          <ul class="dropdown">
            <li><%= link_to origin.name, khmer_path %></li>
            <% elsif origin.id == 2 %>
            <li><%= link_to origin.name, western_path %></li>
            <% end %>
            <% end %>
            </ul>
          </li>
        <li>
          <a href="#">Bands &#9662;</a>
          <ul class="dropdown">
            <li><%= link_to 'Khmer', musicians_path(origin_id: 1) %></li>
            <li><%= link_to 'Western', musicians_path(origin_id: 2) %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hi <%= current_user.username %>! <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <% if current_user.admin? %>
            <li><%= link_to "Dashboard", rails_admin_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% end %>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
        <li><%= link_to 'New Event', new_event_path, class: 'btn btn-primary create-event' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gogigapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  <div>
    <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <% end %>
    </div>
  </div>
  <%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>